### PR TITLE
Fixed documentation for Web API: property artifacts not documents

### PR DESCRIPTION
**Pull request by vorburger**
Signed-off-by: Michael Vorburger <mike@vorburger.ch>

### CODE REVIEW

**Comment by vorburger** [comment]
@spoenemann as far as I can tell from having played around a little in https://github.com/eclipse/xtext/compare/master...vorburger:xtend.web for https://github.com/eclipse/xtext/pull/774 fixed https://github.com/eclipse/xtext/commit/d2c3e2833d75d62df12327057339e4c32291ede5#diff-3eb2b115e4d9d5e386dce6eec0348cc2L171, there is a small error in the documentation, which this PR rectifies - do you agree and would like to merge this?

BTW: Thank You for having written 330_web_support.md in the first place - very useful to get started understanding the (cool!) new Xtext Web support.

**Comment by cdietrich** [comment]
i think this is not working since the generator service uses the artifactId to determine what generation result should be returned and if you dont specify it you get an error. thus i think the generatorService should expose compute as well to return all generated artifacts

**Comment by vorburger** [comment]
@cdietrich I fixed (worked around?) the point you raise via https://github.com/eclipse/xtext/commit/d2c3e2833d75d62df12327057339e4c32291ede5#diff-5b1e78ebdf10acff0ec33045e2f3a548R14

@spoenemann iirelevant of the above, the current doc is still wrong, so I would suggest this either way.

**Comment by spoenemann** [comment]
Documentation updates should be merged into maintenance. If they are merged into master, they won't become visible until the next release (2.10.0).

That part of the documentation is outdated: In one of the beta releases, the generator service returned all generated resources, while now it returns only one resource. This means that your proposed fix is also wrong. I will fix that part on the maintenance branch so we have a correct version on the website soon.

It is true that sometimes the names of the generated artifacts are not known in the client. We could add a service such as `generatorArtifactIds` that returns the names of all artifacts, which can then be fetched with the `generate` service.

**Comment by spoenemann** [comment]
The fix is online: https://www.eclipse.org/Xtext/documentation/330_web_support.html

**Comment by spoenemann** [comment]
Thanks for pointing to the outdated documentation!

**Pull request closed without merging**
