### PR TITLE
[473833] Made resolution of type fragments find inherited types as well.

### PR DESCRIPTION
**Pull request by svenefftinge**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=473833

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins xtend-runtime-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by svenefftinge** [comment]
test failures are unrelated.

**Pull request merged**
