### PR TITLE
[idea][bug 479723] Discard resource on cancellation

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479723

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins test

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
