### PR TITLE
[421967] Consider JDT Type Filter

### PR DESCRIPTION
**Pull request by kthoms**
Change-Id: I95536cf610efd7d4808c841209fddf051205db43
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=421967

**Comment by svenefftinge** [comment]
Nice! Sounds like a useful thing. Could you try adding a test to e.g. org.eclipse.xtend.ide.tests.imports.OrganizeImportsTest

**Comment by kthoms** [comment]
I’ll try that.

**Comment by svenefftinge** [comment]
Jenkins test

**Pull request merged**
