### PR TITLE
[490530] Change variable type of abortOnMissingSource

### PR DESCRIPTION
**Pull request by kthoms**
Change-Id: I13317deeb0718c04df42341c415a73b37fbc53f6
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=490530

**Comment by svenefftinge** [comment]
This will break source compatibility with earlier versions. Could you provide a version that compiles fine with the latest JDT and older versions, too.

**Comment by kthoms** [comment]
I have checked that the version compiles against an older version of org.eclipse.jdt.core, and against a current JDT (which is installed in my dev env). The difference is only that the @SuppressWarnings("unchecked“) becomes obsolete with the new JDT and gets a warning. With an older JDT, the @SuppressWarnings is not marked with a warning.

In JDT code, the field is only set with a Boolean instance and checked against that. Thus I consider this fix as compatible.

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by svenefftinge** [comment]
Thanks!

**Pull request merged**
