### PR TITLE
update to mwe(2) 1.11.0/2.17.0 M0

### PR DESCRIPTION
**Pull request by cdietrich**
please double check i did not overlook something

### CODE REVIEW

**Review by szarnekow — APPROVED** [review]

**Comment by szarnekow** [comment]
Changes look good but the build fails to find mwe 2.17.

**Comment by LorenzoBettini** [comment]
@cdietrich the build still fails

```
Error:  Cannot resolve project dependencies:
Error:    Software being installed: org.eclipse.xtext.xtext.ui 2.34.0.qualifier
Error:    Missing requirement: org.eclipse.xtext.xtext.ui 2.34.0.qualifier requires 'osgi.bundle; org.eclipse.emf.mwe2.language 2.17.0' but it could not be found
```

**Comment by cdietrich** [comment]
I assume the workaround is needed in more targets :(

**Comment by LorenzoBettini** [comment]
@cdietrich sorry, I thought you'd updated them all.

**Review by LorenzoBettini — APPROVED** [review]

**Pull request merged**
