### PR TITLE
Handle empty bundle symbolic name

### PR DESCRIPTION
**Pull request by rosczja**
See #2677

### CODE REVIEW

**Comment by cdietrich** [comment]
wonder what about similar places like

org.eclipse.xtext.builder.standalone.incremental.ResourceURICollector.registerBundle(File)
org.eclipse.xtext.builder.standalone.StandaloneBuilder.registerBundle(File)

**Comment by szarnekow** [comment]
@rosczja Could you please add the same guard to both classes that @cdietrich mentioned?

**Comment by rosczja** [comment]
Added the same check into the two files @cdietrich mentioned

**Review by szarnekow — APPROVED** [review]
Thank you

**Comment by cdietrich** [comment]
thx @rosczja

**Pull request merged**
