### PR TITLE
another classgraph bump 4.8.176

### LINKED ISSUE #3199: Classgraph version bump
4.8.175 is not available anymore in Orbit, which now provides 4.8.176.

Since in the generated projects from the wizard we got rid of the pinned version, can I do the same in our target platforms?
cc @cdietrich

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #3199

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
This increased the version in the target and POM, but in the issue I was suggesting to get rid of the pinned version (at least in the target files)

**Review by cdietrich — APPROVED** [review]
ok, what about the manifests.

**Comment by LorenzoBettini** [comment]
> ok, what about the manifests.

For the moment I've just increased the minimum version in the MANIFEST as well

**Review by cdietrich — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
@cdietrich I've updated the PR version range in the MANIFEST, unpinned the version from TP, and updated the dependabot configuration according to my understanding of it.

**Comment by LorenzoBettini** [comment]
@cdietrich I merged and looks like it's working as expected (https://github.com/eclipse/xtext/actions/runs/10926606231/job/30330860901):

```
2024/09/18 16:49:53 INFO <job_887152119> Checking all dependencies for version updates...
updater | 2024/09/18 16:49:53 INFO <job_887152119> Checking if io.github.classgraph:classgraph 4.8.176 needs updating
  proxy | 2024/09/18 16:49:54 [012] GET [https://repo.maven.apache.org:443/maven2/io/github/classgraph/classgraph/maven-metadata.xml](https://repo.maven.apache.org/maven2/io/github/classgraph/classgraph/maven-metadata.xml)
  proxy | 2024/09/18 16:49:54 [012] 200 [https://repo.maven.apache.org:443/maven2/io/github/classgraph/classgraph/maven-metadata.xml](https://repo.maven.apache.org/maven2/io/github/classgraph/classgraph/maven-metadata.xml)
updater | 2024/09/18 16:49:54 INFO <job_887152119> Filtered out 2 pre-release versions
  proxy | 2024/09/18 16:[49](https://github.com/eclipse/xtext/actions/runs/10926606231/job/30330860901#step:3:51):54 [016] HEAD https://repo.maven.apache.org:443/maven2/io/github/classgraph/classgraph/4.8.176/classgraph-4.8.176.jar
  proxy | 2024/09/18 16:49:54 [016] 200 [https://repo.maven.apache.org:443/maven2/io/github/classgraph/classgraph/4.8.176/classgraph-4.8.176.jar](https://repo.maven.apache.org/maven2/io/github/classgraph/classgraph/4.8.176/classgraph-4.8.176.jar)
updater | 2024/09/18 16:49:54 INFO <job_887152119> Latest version is 4.8.176
updater | 2024/09/18 16:49:54 INFO <job_8871[52](https://github.com/eclipse/xtext/actions/runs/10926606231/job/30330860901#step:3:54)119> No update needed for io.github.classgraph:classgraph 4.8.176
```

That's the only Maven artifact mentioned in the log.

**Pull request merged**
