### PR TITLE
Bug 468641 [xbase] issues with JvmTypesBuilder toGetter/toSetter

### PR DESCRIPTION
**Pull request by LorenzoBettini**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=468641

Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=468641

**Comment by svenefftinge** [comment]
Actually it is perfectly ok, to resolve the proxy here. 
The only thing that we must avoid is to resolve an XComputedTypeReference.

**Comment by LorenzoBettini** [comment]
If the proxy is resolved at that point (during toGetter), then https://bugs.eclipse.org/bugs/show_bug.cgi?id=468174 won't work, but I saw that you left a comment in that bug as well, about the solution being wrong.

However, from what I understand, toGetter is the only place where proxy resolution is not delayed, and I seemed to understand that proxies should not be resolved during the model inferrer, that's why I thought that the current implementation was somehow wrong anyway.

The additional cloning of the parameter's type in toSetter looks wrong anyway.

**Comment by svenefftinge** [comment]
The caution you see in the code is a relict of times when we hadn't fully understood what could be done and what not. :-| 
During (post indexing) model inference it is ok to type proxies. It is only not ok to depend on JvmType's members (since we are in the process of creating them).

**Comment by LorenzoBettini** [comment]
So should I modify the patch so that only toSetter implementation is changed? I think that the additional cloning in toSetter is wrong anyway :)

And we keep on discussing the other bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=468174 there?

**Comment by svenefftinge** [comment]
Extracting the method isBooleanType is also a good improvement. But it should just check for isInferred and otherwise directly check getType.

**Comment by LorenzoBettini** [comment]
So now getType is used to check whether it's a primitive boolean (if not inferred); I also made it protected API (if I understand correctly what you said).

**Comment by LorenzoBettini** [comment]
Hi, did you see the updated commits?

**Comment by svenefftinge** [comment]
Thanks!

**Pull request merged**
