### PR TITLE
Add option includePluginDependencies to xtext-maven-plugin

### LINKED ISSUE #2665: Add option `includePluginDependencies` to `xtext-maven-plugin`
It's sometimes useful to include the classpath of plugin dependencies when generating code using the `xtext-maven-plugin`.

See use case here: https://www.eclipse.org/forums/index.php/m/1859085/#msg_1859085.

The `xtext-maven-plugin` could add an option such as `includePluginDependencies`, much like how the `maven-exec-plugin` does it (see [this method](https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java#LL690C39-L690C39), which accesses the plugin dependencies via the maven variable `${plugin.artifacts}`).

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #2665

### CODE REVIEW

**Review by szarnekow — APPROVED** [review]
Thank you for adding a test, too

**Comment by LorenzoBettini** [comment]
@SimonCockx could you please confirm that this fixes your problem?

You should use 2.31.0-SNAPSHOT for the xtext-maven-pluin and use this temporary Maven repository https://ci.eclipse.org/xtext/job/xtext/job/lb_2665_includePluginDependencies/lastSuccessfulBuild/artifact/build/maven-repository/ 

I'm waiting for your feedback before merging this PR.

Since we're close to the release, the sooner the better, please :)

**Review by SimonCockx — APPROVED** [review]

**Comment by SimonCockx** [comment]
> @SimonCockx could you please confirm that this fixes your problem?
> 
> You should use 2.31.0-SNAPSHOT for the xtext-maven-pluin and use this temporary Maven repository https://ci.eclipse.org/xtext/job/xtext/job/lb_2665_includePluginDependencies/lastSuccessfulBuild/artifact/build/maven-repository/
> 
> I'm waiting for your feedback before merging this PR.
> 
> Since we're close to the release, the sooner the better, please :)

I can confirm that this does the job. Thank you!

**Comment by LorenzoBettini** [comment]
@cdietrich OK to merge?

**Comment by cdietrich** [comment]
as said. i dont like the solution but i am ok with it.

**Pull request merged**
