### PR TITLE
Provide an Oomph configuration

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@cdietrich  @LorenzoBettini 

Of course this can be refined and modified to suit your needs.  Once has been committed, a badge icon should be generated and I can help you link like I showed for other projects.  (But I travel soon and have little time this week.)

**Comment by LorenzoBettini** [comment]
@merks I wasn't aware of this feature, thanks!

Can we experiment with that with the current PR somehow?

@cdietrich shall we try that?

**Comment by cdietrich** [comment]
We can but I won’t find time to try it out myself

**Comment by merks** [comment]
If you check out the PR into a workspace, you can drag and drop the XtextConfiguration.setup resource itself onto an installer's title area to try it out.  

Until it's checked in, the documentation link will not display the description HTML like it does for this page:

https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-oomph/oomph/master/setups/configurations/OomphConfiguration.setup&show=true

And there will not exist a generated badge like this one:

https://download.eclipse.org/oomph/www/setups/svg/oomph.svg

Both of those are supported only by the processing done by this job after you commit the changes:

https://ci.eclipse.org/oomph/job/setup-archiver/

Note that its important that the Xtext setup has a reference to the configuration as I've done here. 

When this is committed, I can help further.  (And it goes without saying that of course you can change it in the future should you think other ways to simplify/guide the user's choices.)

**Comment by merks** [comment]
It's a bit ironic that a contribution intended purely to make contribution easier (a contribution that has no impact on existing functionality neither in the code nor in the existing Oomph project setup) languishes for a week.  I expect everyone is very busy with other things just like me so I do understand, but, if I were average-Jane user, I would be a little more annoyed with every passing day

**Comment by cdietrich** [comment]
> (a contribution that has no impact on existing functionality neither in the code nor in the existing Oomph project setup

this I could not derive from the pr without trying it out myself

**Comment by cdietrich** [comment]
Let’s see what happens if this is deployed

**Comment by LorenzoBettini** [comment]
> It's a bit ironic that a contribution intended purely to make contribution easier (a contribution that has no impact on existing functionality neither in the code nor in the existing Oomph project setup) languishes for a week. I expect everyone is very busy with other things just like me so I do understand, but, if I were average-Jane user, I would be a little more annoyed with every passing day

@merks indeed I had a busy week. Otherwise, I'd usually be more reactive O:)

**Comment by merks** [comment]
Here is the markup you can use in any *.md file:

[Create Eclipse Development Environment for Xtext](https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse/xtext/main/releng/org.eclipse.xtext.contributor/XtextConfiguration.setup&show=true "Click to open Eclipse-Installer Auto Launch or drag onto your running installer's title area")

E.g., on your contributing page in this section:

---

The page it opens looks like this:

image

---

Using it, the installer advances to this page:

image

Because on the first page it selected this:

image

And the second page it selected this:

image

**Pull request merged**
