### PR TITLE
Update to LSP4J 0.23.0. Fixes #2933

### LINKED ISSUE #2933: Update to LSP4J 0.23.0
Update to LSP4J 0.23.0

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Comment by cdietrich** [comment]
we update notice.md only for 2rd party deps, not eclipse ones

**Comment by cdietrich** [comment]
@LorenzoBettini did you figure out why

>  @github-actions
> Build / build (pull_request) Skipped

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini did you figure out why
> 
> > @github-actions
> > Build / build (pull_request) Skipped

@cdietrich the fact that build jobs for PR are skipped is expected: we implemented that for skipping PRs for internal PRs.

I don't understand why the build jobs for the PUSH are skipped... that's unexpected.

**Comment by cdietrich** [comment]
This is what I meant

**Comment by LorenzoBettini** [comment]
> This is what I meant

Can it be that you created the edits directly from GitHub?
Just guessing...
it happened twice for you.

**Comment by cdietrich** [comment]
No I pushed branch and immediately created pr

**Comment by LorenzoBettini** [comment]
Then maybe you've been too fast ;)
let's see in the future.

**Pull request merged**
