### PR TITLE
[473079] Provide a platform neutral trace API and platform specific enhancements

### PR DESCRIPTION
**Pull request by szarnekow**
Work in progress.

Removed dependency to core.resources from org.eclipse.xtext

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=473079

**Comment by svenefftinge** [comment]
looks like you are using an old xtend compiler

**Comment by svenefftinge** [comment]
Ok, that is indeed the latest version. 
The fix for [1] seems to be the cause for the differences.
Is that intentional?
[1] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=472142

**Comment by szarnekow** [comment]
Intentional ... yes and no. I would have liked to have prettier code, but the pretty version was sometimes incorrect and I didn't find an unobstrusive way to detect if we need the pretty or not-so-pretty version. So I figured we'll prefer correctness over readability

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
