### PR TITLE
[bug 471561][extract method refactoring] Declare a return type and set the visibility to 'protected' by default

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471561

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by svenefftinge** [comment]
:+1:

**Pull request merged**
