### PR TITLE
[492456] Added support for ignorecase-keywords to the new serializer

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=492456

**Comment by cdietrich** [comment]
@meysholdt can you please review

**Comment by meysholdt** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by meysholdt** [comment]
👍 
feel free to merge

**Pull request merged**
