### PR TITLE
[bug 488380]  revised dirty state support

### PR DESCRIPTION
**Pull request by JanKoehnlein**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488380

**Comment by JanKoehnlein** [comment]
Jenkins xtend-ide-tests-fast

**Comment by JanKoehnlein** [comment]
Jenkins xtext-ide-tests-maintenance-latest

**Comment by JanKoehnlein** [comment]
Jenkins xtend-ide-tests-maintenance-latest

**Pull request merged**
