### PR TITLE
[bug 482380] Isolate Annotation Processor Classloader from annotations on plug-in class path

### PR DESCRIPTION
**Pull request by akosyakov**
Change-Id: I105f93caac280fa9d1b8f011d08b5cfd027f2b9a
Signed-off-by: akosyakov <anton.kosyakov@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482380

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins test

**Pull request merged**
