### PR TITLE
Fix for Bug 486584

### PR DESCRIPTION
**Pull request by cdietrich**
Do not trigger FullBuild if ClasspathChange is a SourceAttachmentChange only. Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=486584

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=486584

**Comment by cdietrich** [comment]
hmmmm having the same code on 3 pleases seems odd. do you see a change to unify them or should i copy & paste the fix around these files

**Comment by svenefftinge** [comment]
I haven't checked whether there are subtle differences, and if whether they are intended. 
But unifying would be great!

**Comment by cdietrich** [comment]
AbstractJavaProjectsState does have a different signature and uses eager exit regarding recursion, so i would change this in place

**Comment by cdietrich** [comment]
And the other question world be where to put the change. the builder and ui plugin have no dep to each other

**Comment by cdietrich** [comment]
i have updated the pull request. but the build does not seem to be retriggered

**Comment by svenefftinge** [comment]
The builder plugin has a dependency to xtext.ui

**Comment by cdietrich** [comment]
yes that works. so i could unify at least 2 places. non the less i kept ProjectClasspathChangeListener api compatible

**Comment by svenefftinge** [comment]
Please also extract and reuse methods for the third place where it makes sense

**Comment by cdietrich** [comment]
does it look better now?

**Comment by svenefftinge** [comment]
Jenkins Test

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by cdietrich** [comment]
pushed a fix for Storage2UriMapperJavaImplTest
XtendCopyQualifiedNameServiceTest works fine on my machine. i have no idea what made this one red

**Comment by svenefftinge** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by cdietrich** [comment]
any news on this?

**Pull request merged**
