### PR TITLE
Added screenshots to releasenotes

### PR DESCRIPTION
**Pull request by epoell**
Signed-off-by: Eva Poell <epoell@itemis.com>

### CODE REVIEW

**Comment by epoell** [comment]
ah sorry, the images do not work yet

**Comment by cdietrich** [comment]
have a look at for an example https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2018-09-04-version-2-15-0.md

they dont work in github preview

**Comment by cdietrich** [comment]
=> needs to be tested locally with jekyll

**Comment by epoell** [comment]
yes, I think they do actually work, bit I forgot to build it locally.
I'm installing jekyll just now

Thanks :)

**Comment by epoell** [comment]
OK I built it with jekyll and the server runs, but I cannot access the releasenotes for 2.17.
Any hints, where I have to change or add some settings?

**Comment by cdietrich** [comment]
there is a publish flag in the doc. and you can tell jekyll to show unpublished as well.
`--future` or `--unpublished`

**Comment by epoell** [comment]
It worked, nice :)

The screenshots are fine, too, I think, I now really want to request the pull!

**Pull request merged**
