### PR TITLE
Maintenance Bug 471434 - [contentassist][generator] the ContentAssist fragment should consider redefined grammar rules

### PR DESCRIPTION
**Pull request by LorenzoBettini**
These are the cherry picks from https://github.com/eclipse/xtext/pull/320 to the maintenance branch.

It also includes two additional commits to regenerate the test languages and to change the @since annotation in the added class.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471434

**Comment by szarnekow** [comment]
Jenkins test

**Comment by LorenzoBettini** [comment]
I think the failed job is not due to this patch, since also other jobs are failing

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Merged. Thank you, Lorenzo!

**Pull request merged**
