### PR TITLE
[263773] Xtext grammar enhancements

### PR DESCRIPTION
**Pull request by szarnekow**
This is the first shot at various enhancements for the Xtext grammar language.
The following features have been added:

- Explicit rule calls and super rule calls
  - `name=super::ID`
  - `name=Terminals::ID`
  - `feature=com::acme::MyLang::SomeRule`
  - `MyRule: super | some other syntax;`
- Parser rule fragments
  - `fragment DeclarationOwner:
      declarations+=Declaration+;`
- Parameterized rule calls:
  - `IdOrKeyword<AllowKeyword>:
      <AllowKeyword> ‘keyword’ | ID;`

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=263773

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
