### PR TITLE
Bug 483162 - [generator] o.e.x.x.generator.model.TypeReference has not the right pattern to match package and class name

### PR DESCRIPTION
**Pull request by masofcon**
Changed package name validation pattern. Now it allows '_' and '$' in
package name. 

Signed-off-by: George Suaridze <suag@1c.ru>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=483162

**Comment by dhuebner** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Test failures are unrelated.

It looks to me as if the class name pattern has the same problems. Could you please update the PR? It would be great if you could also add new test cases in org.eclipse.xtext.generator.TypeReferenceTest

**Comment by masofcon** [comment]
@szarnekow OK, I'll try to do it in several days.

**Comment by svenefftinge** [comment]
I've removed the patterns and guards all-together see #840

**Pull request closed without merging**
