### PR TITLE
Fix typo in tutorial

### PR DESCRIPTION
**Pull request by janniks**

### CODE REVIEW

**Comment by kthoms** [comment]
@janniks Thanks for reporting. Sorry to bother you, but in order to merge it would be necessary to sign a CLA and sign-off your commit to pass the IP validation.
Either you do that, or I would create another change myself. What do you prefer?
If you are planning to provide other patches as well, which would be welcomed, I would ask you to go the mandatory process.

**Comment by janniks** [comment]
@kthoms Done ✅

**Comment by kthoms** [comment]
Hi @janniks ,

thanks so far, but the commit must have to be signed off. This basically means that your commit message must end with
```

Signed-off-by: YOUR NAME <your@mail>
```
The email address must match the address you used for your Eclipse account. Note the empty line before `Signed-off-by`.

The GitHub web editing does not support the process so well. Sorry for this inconvenience. Looking forward to any contribution, that's welcome!

**Comment by kthoms** [comment]
Please ammend the commit, so that the original commit is changed.

**Comment by kthoms** [comment]
The first PR is always the hardest ;)

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext/pull/1187

**Comment by janniks** [comment]
Damn, beat me to it 😅

**Comment by cdietrich** [comment]
ill do it next time ;)

**Pull request closed without merging**
