### PR TITLE
[482116] Fixed bug in GrammarAccessFragment

### PR DESCRIPTION
**Pull request by szarnekow**
Super rule calls could confuse the getter impl in the
grammar access.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482116

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by svenefftinge** [comment]
If a super language overrides a certain rule later on, then it will no longer be considered by the sub language. I don't think it's a big issue, as sublanguages would usually need to be regenerated anyway.

It would be good to have the failing scenario added as a test language.

**Comment by szarnekow** [comment]
Regarding newly added override in some super lang: This scenario was always a breaking change since the since the the return type of `getMyRuleAccess` would have changed from `SuperLangGrammarAccess.MyRuleAccess` to `SubLangGrammarAccess.MyRuleAccess`. IMHO it's more robust after that change.

Will add a test-case.

**Comment by svenefftinge** [comment]
ok, good!

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Pull request merged**
