### PR TITLE
470586: useless if check for the first switch's case

### PR DESCRIPTION
**Pull request by LorenzoBettini**
[xbase][compiler] useless if check for the first switch's case

https://bugs.eclipse.org/bugs/show_bug.cgi?id=470586

This avoids the useless generation of the if (!_matched) check for the translated first case of an if.
The useless if check makes Jacoco report missing branches for all the Java code generated by Xtend that uses a switch statement.

I ran core tests locally, but I can't exclude some test failures for other tests I haven't considered, so a Jenkins test would help :)

### CODE REVIEW

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by LorenzoBettini** [comment]
phew... all tests are still green :)

Do you want me to regenerate all the Xtend Java generated files in a separate commit, if this PR is acceptable?

**Comment by svenefftinge** [comment]
Let's run some more

**Comment by svenefftinge** [comment]
Jenkins xtend-runtime-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by svenefftinge** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by svenefftinge** [comment]
Cool, thank you!

**Comment by LorenzoBettini** [comment]
Great :)
Do you want me to regenerate all the Xtend Java generated files in a separate commit? Or are you going to take care of that?

**Comment by svenefftinge** [comment]
That would be good!

**Comment by dhuebner** [comment]
@LorenzoBettini Unfortunately our hudson job which uses the Xtend Compiler to recompile the xtext WS started to fail:
java.lang.AssertionError: Problems found (2 of 2): Duplicate local variable _function in /org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreator.java line: 96, Java problem: Duplicate local variable _function in /org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreator.xtend line: 50
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.xtext.junit4.internal.InternalBuilderTest.test(InternalBuilderTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)

**Comment by LorenzoBettini** [comment]
ops! :(
then I guess the merge should be reverted, and I'll try to reproduce the problem with a unit test.
I guess that's related to appendable's scope not being properly closed and this leads to the appendable to create a variable with the same name.
Sorry for the inconvenience.

**Comment by LorenzoBettini** [comment]
@dhuebner I think I found the problem.
What's the best way to proceed?

- revert the merge and I push on the same PR?
- create a new PR based on master?

**Comment by svenefftinge** [comment]
Just add another PR

**Comment by LorenzoBettini** [comment]
Done, https://github.com/eclipse/xtext/pull/991

**Pull request merged**
