### PR TITLE
[475337] - Made JvmModelGenerator more robust against incomplete models. Handle null passed to TreeAppendable#append more gracefully.

### PR DESCRIPTION
**Pull request by svenefftinge**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=475337

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Shouldn't we also make sure that we do not produce enum literals without a name?

**Comment by svenefftinge** [comment]
I think, it is better to pass on a literal without a name. Especially, since we cannot enforce such a contract on every Xbase client.

**Comment by szarnekow** [comment]
We filter all other members that have a null name and do not produce JVM equivalents for them (for good reasons, since most of the code wouldn't expect JvmIdentifiable.getSimpleName to return null). It should at least be symmetric for enum literals. I would be in favor of filtering members with a null name.

**Comment by svenefftinge** [comment]
So you mean filtering those for Xtend in addition to being null-tolerant in the JvmModelGenerator?

**Comment by szarnekow** [comment]
Filtering in addition. See also JvmTypesBuilder.toXYZ(..) which are all guarded by if (name==null) return null

**Comment by szarnekow** [comment]
Which makes me wonder why we do not call org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toEnumerationLiteral(EObject, String) in the Xtend inferrer

**Comment by szarnekow** [comment]
I see - because we do not really use the types builder in the xtend inferrer but only for a few special things.

**Comment by svenefftinge** [comment]
AFAICS we also don't check XtendFunctions for getName, but it seems like there is no way the parser would create such an AST.

**Comment by szarnekow** [comment]
It's checked here:
if (member instanceof XtendField
					|| (member instanceof XtendFunction && ((XtendFunction) member).getName() != null)
					|| member instanceof XtendConstructor) {
				transform(member, inferredJvmType, true);
			}

**Comment by szarnekow** [comment]
Maybe we also want to add a test. I think the bug is reproduced by this enum:
```
enum MyEnum {
	First ,, Third	
}
```

**Pull request merged**
