### PR TITLE
[431435] Bind generated EPackage and EFactory

### PR DESCRIPTION
**Pull request by kthoms**
Change-Id: I8590497bbb1f25292f185d630e4e8c9f485d7f3b
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=431435

**Comment by svenefftinge** [comment]
When changing the code generator we need to regenerate all the languages, too. We usually do that in a separate commit in the same PR.

**Comment by kthoms** [comment]
OK. I’ll do that.

**Comment by svenefftinge** [comment]
Please also regenerate xtend, xtext, xbase and the examples.

**Comment by kthoms** [comment]
The bindings are only added when EMFGeneratorFragment / EMFGeneratorFragment2 is executed in the workflow. For Xtext, Xbase & Xtend the bindings are not automatically added, since they do not generate the EMF metamodel.

Is the EMFGeneratorFragment2 the right fragment or should this be handled more generic. But how to distinguish between the EMF packages "owned" by the language and those that are just used?

Should I add the bindings to the concrete runtime class for those languages manuall?

**Comment by svenefftinge** [comment]
My bad. It's ok to not do that for external EPackages.

One last thing, could you add a property to the fragment to turn the generation off the bindings on, and have it off by default. The reason I'd prefer it to be off by default, is that we almost never use DI for these two types because there is no good reason to do it (especially not for EPackages) and I prefer to encourage the use of the standard EMF-way (use singletons) instead, as there is too much code that relies on that already. And we do it like that, as well.
That said its ok to have that option, if you want to have it.

**Comment by kthoms** [comment]
Due to repository restructuring replaced by
https://github.com/eclipse/xtext-core/pull/75
https://github.com/eclipse/xtext-extras/pull/34

**Pull request closed without merging**
