### PR TITLE
bug462217: update message for anonymous classes

### PR DESCRIPTION
**Pull request by vladdu**
Update message for all cases.

### CODE REVIEW

**Comment by oehme** [comment]
[Jenkins Bot] Can a team member please verify that this is good for testing?

**Comment by vladdu** [comment]
Weird that Github shows that the "if" statement didn't change indentation, but it looks right in my editor.

**Comment by oehme** [comment]
Jenkins test

**Comment by svenefftinge** [comment]
Jenkins test

**Pull request merged**
