### PR TITLE
Fixed jvm inferrer docs

### PR DESCRIPTION
**Pull request by cdietrich**
Fixed jvm inferrer docs

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by dhuebner** [comment]
@cdietrich Why not against website-published branch?

**Comment by cdietrich** [comment]
i dont know what the process is

**Comment by cdietrich** [comment]
when and how is stuff merged between the website branches @dhuebner @spoenemann

**Comment by dhuebner** [comment]
@cdietrich All changes commited to the website-published are build and published automatically by eclipse hudson. I have no idea what is website-master for

**Comment by cdietrich** [comment]
i know. i am wondering if i have to pull against both or if there is a magic merge process

**Comment by dhuebner** [comment]
No merging between them. Only website-published is relevant

**Comment by cdietrich** [comment]
but where is the 2.12 stuff developed?

**Comment by kthoms** [comment]
2.12 is on website-master AFAIK.

**Comment by dhuebner** [comment]
Is your change for 2.12 ?
However, documentation is normally written in a privat branch just before release. And merged with a PR

**Comment by cdietrich** [comment]
no i simply want to fixed bugs stuff in the website.
why do we have websitemaster at all?

**Comment by cdietrich** [comment]
i just want to make sure

- we dont get stupid merge conflicts
- nothing gets lost

**Comment by kthoms** [comment]
If you commit to website-published then changes to there should be able to be merged safely to website-master w/o conflicts usually.

**Comment by cdietrich** [comment]
well not if somebody changes master meanwhile

**Comment by cdietrich** [comment]
i changed the base to website-published.
@spoenemann should i do another pull request against website-master?

**Comment by spoenemann** [comment]
No, not necessary. We can merge `website-published` into `website-master` before we do the 2.12 release.

**Comment by cdietrich** [comment]
ok. so i can merge this now to published?

**Pull request merged**
