### PR TITLE
[434982] better fix for keyword conflicts in dispatch method if else …

### PR DESCRIPTION
**Pull request by cdietrich**
…cascade

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=434982

**Comment by cdietrich** [comment]
Jenkins test

**Comment by cdietrich** [comment]
@akosyakov can you have a look at this

**Comment by cdietrich** [comment]
Jenkins xtend-runtime-tests-master-latest

**Comment by akosyakov** [comment]
looks good, please merge

**Pull request merged**
