### PR TITLE
Fixed ISE when removing a resource from resource set

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by szarnekow** [comment]
If the stopwatch was never started, `stop()` throws the ISE, `reset()` doesn't

**Comment by LorenzoBettini** [comment]
@szarnekow OK, got it!

**Comment by LorenzoBettini** [comment]
@szarnekow the build on macOS started to fail after the merge of this PR:

```
Error:  Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.7:test (default-test) on project org.eclipse.xtext.purexbase.eclipse.tests: An unexpected error occurred while launching the test runtime (process returned error code 13). Command-line used to launch the sub-process was /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/arm64/Contents/Home/bin/java -Dosgi.noShutdown=false -Dosgi.os=macosx -Dosgi.ws=cocoa -Dosgi.arch=aarch64 -Xmx1500m -XstartOnFirstThread -Dosgi.clean=true -jar /Users/runner/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.800.v20240330-1250/org.eclipse.equinox.launcher-1.6.800.v20240330-1250.jar -data /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/work/data -install /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/work -configuration /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/work/configuration -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/surefire.properties -pluginCustomization /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/../org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini in working directory /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests -> [Help 1]
```

I also tried to restart the job but it always fails at that point.

**Comment by szarnekow** [comment]
```
/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64/Contents/Home/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=macosx, -Dosgi.ws=cocoa, -Dosgi.arch=x86_64, -Dosgi.clean=true, -jar, /Users/runner/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.800.v20240330-1250/org.eclipse.equinox.launcher-1.6.800.v20240330-1250.jar, -data, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.tests/target/work/data, -install, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.tests/target/work, -configuration, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.headlesstest, -testproperties, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.tests/target/surefire.properties
```

This is cmd line of the successful mvn build before the merge (note that it uses x86).
The failing build:
```
/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/arm64/Contents/Home/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=macosx, -Dosgi.ws=cocoa, -Dosgi.arch=aarch64, -Xmx1500m, -XstartOnFirstThread, -Dosgi.clean=true, -jar, /Users/runner/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.800.v20240330-1250/org.eclipse.equinox.launcher-1.6.800.v20240330-1250.jar, -data, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/work/data, -install, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/work, -configuration, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/target/surefire.properties, -pluginCustomization, /Users/runner/work/xtext/xtext/org.eclipse.xtext.purexbase.eclipse.tests/../org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini, -timeout, 2400000
```
The merge cannot cause this change - it now uses arm64 but the TP doesn't contain the SWT native libs for arm according to his message:
```
Warning:  Your build environment {osgi.os=macosx, osgi.ws=cocoa, osgi.arch=aarch64} does not match any of the configured target environments [macosx/cocoa/x86_64, win32/win32/x86_64, linux/gtk/x86_64]. Test execution might be inconsistent
```

**Comment by cdietrich** [comment]
we dont have any arms in environments of target-platform-configuration

**Comment by LorenzoBettini** [comment]
Looks like they changed the defaults: https://github.com/actions/runner-images: `macos-latest` is now arm.
We should switch to `macos-latest-large`.
I'll try that ASAP

**Comment by szarnekow** [comment]
> macos-latest-large

Should we use a stable tag instead of latest?

**Comment by LorenzoBettini** [comment]
> > macos-latest-large
> 
> Should we use a stable tag instead of latest?

even better!

**Pull request merged**
