### PR TITLE
Lb 2158 cleanup maven plugins i ts

### LINKED ISSUE #2158: Cleanup Maven plugins ITs
@cdietrich @szarnekow this line https://github.com/eclipse/xtext/blob/main/org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml#L13 scares me a lot!

It means that we run the IT projects using the currently released version of Xtext, NOT the currently developed version. We might release a new version of xtend-maven-plugin that does not work with the same released version of Xtext.

I'd apply the same strategy as in https://github.com/xtext/xtext-monorepo/pull/17 so that the integration tests are using the same artifacts of the current sources, OK?

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #2158 

As shown in the temporary experimental branch https://github.com/eclipse/xtext/tree/lb_2158_cd_2174 this fixes also the problems of https://github.com/eclipse/xtext/pull/2187

Note also some additional explicit Maven deps in https://github.com/eclipse/xtext/commit/c00d6a7751a3b8bf308f298b6759ead07fb5e25e (that correspond to the ones in MANIFEST)

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini  can you please assign prs to current milestone so that the easily can be traced.

**Review by cdietrich — APPROVED** [review]
approved given the build is green

**Comment by LorenzoBettini** [comment]
@cdietrich milestone assigned; let's wait for the build

**Comment by LorenzoBettini** [comment]
> approved given the build is green

sorry: "given" means that since it is green I can merge or that we should wait for the build of PRs? The pushed branch builds are already green.

**Comment by cdietrich** [comment]
no waiting is not neeeded @LorenzoBettini 
question:
can we restrict the pr build on github actions for fork based prs?
the branches will be built anyway
that could lift some weight from github actions

**Comment by LorenzoBettini** [comment]
> no waiting is not neeeded @LorenzoBettini question: can we restrict the pr build on github actions for fork based prs? the branches will be built anyway that could lift some weight from github actions

@cdietrich yes, I think there's a way. But that means you cannot check whether the PR from an external fork breaks the build once merged. Or did you mean something else?

**Comment by cdietrich** [comment]
@LorenzoBettini no i mean the other ways round
- if the pr is coming from a branch, just build branch, skip the pr
- if the pr is coming from a fork, build the pr on github action

**Comment by LorenzoBettini** [comment]
Let's see whether it's easy...

However, if we skip the build of a PR for one of our internal branches, we must always remember to be aligned with the `main` branch to get the same guarantees of a build of a PR.

**Comment by cdietrich** [comment]
yes this basically is what we did the last 7 years ;)

**Pull request merged**
