### PR TITLE
Fixed Test that does not clean up afterwards

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by svenefftinge** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins test

**Comment by dhuebner** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Change looks good to me.

**Pull request merged**
