### PR TITLE
[bug 476534] Avoid compilation of feature calls of void type as expressions

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476534

**Comment by svenefftinge** [comment]
:+1:

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Sorry, my fault - the mobile github page fooled me :)

**Pull request merged**
