### PR TITLE
[493784] Clean JvmTypeChangeDispatcher when discarding derived state

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich christian.dietrich@itemis.de

### CODE REVIEW

**Comment by cdietrich** [comment]
Jenkins xtend-runtime-tests-master-latest

**Comment by kthoms** [comment]
Method cleanJvmTypeChangeDispatcher could be private

**Comment by svenefftinge** [comment]
We need a clean up strategy for TypeResources, too. I think a general 'unload' method on JvmDeclaredTypeImplCustom that removes the registered runnables would be good. That should in turn be called by the JvmModelAssociator and the unload hook in TypeResource.

If you have a workaround I'd like to postpone this change for after 2.10.

**Comment by spoenemann** [comment]
If the change is still relevant, please reapply it to xtext-extras and xtext-xtend.

**Comment by cdietrich** [comment]
it is still relevant but i still dont have any new input from sven on this topic
(what is our cleanup strategy for type resources)

**Pull request closed without merging**
