### PR TITLE
[xtend] Bug 462313: Problem with synthetic _this variable for anonymous classes

### PR DESCRIPTION
**Pull request by spoenemann**
protected members may not be visible if accessed through a synthetic _this variable.

### CODE REVIEW

**Comment by szarnekow** [comment]
Could please add a test that combines the scenario of this bug with the scenario that required to _this field? Do we see a proper validation for the seemingly not compilable code?

**Comment by spoenemann** [comment]
Currently the `_this` is generated even if it's not absolutely necessary. The proposed change suppresses it in cases where it would reduce the visibility (protected members). Cases where the `_this` is really necessary *and* we have a reference to a protected member from another package would be compiled incorrectly:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=458429
A respective validation is still missing, but that could be done for bug 458429 (hence not for v2.8.1)?

**Comment by szarnekow** [comment]
Agreed.

**Comment by szarnekow** [comment]
Jenkins test

**Pull request merged**
