### PR TITLE
Update minimum Supported Java version in Xbase and Xtend to Java 8

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Comment by cdietrich** [comment]
from my pov we are good to go. wdyt @szarnekow

**Comment by cdietrich** [comment]
am not sure if we need to do something like
org.eclipse.xtext.ui.testing.util.JavaProjectSetupUtil.makeJava7Default()

**Comment by szarnekow** [comment]
> org.eclipse.xtext.ui.testing.util.JavaProjectSetupUtil.makeJava7Default()

Wow that's annoying logic

**Comment by szarnekow** [comment]
But luckily it only cloaks a Java7 JRE as a Java6 JRE

**Review by LorenzoBettini — APPROVED** [review]
@cdietrich @szarnekow thank you both for updating all these tests!

**Pull request merged**
