### PR TITLE
[serializer] several fixes

### PR DESCRIPTION
**Pull request by meysholdt**
- pass ParserRule-Parameters to Action-based contexts
- fixed an issue with constraint names that could cause duplicate 
  Java method names in the Semanitc Sequencer
- improved names of serialization contexts

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@itemis.de>

### CODE REVIEW

**Comment by meysholdt** [comment]
Jenkins 	xtext-runtime-tests-master-latest

**Comment by meysholdt** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
With the current state of the PR, I still see plenty of `//java.lang.RuntimeException:` in the grammar access

**Comment by meysholdt** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Nice, no more RuntimeExceptions with the latest from the branch!

**Comment by meysholdt** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Pull request merged**
