### PR TITLE
[448483] prevent npe in content assist for zero param operator_* methods

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=448483

**Comment by cdietrich** [comment]
Jenkins Test

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by cdietrich** [comment]
the two failing tests are green on my local machine. what could be causing their failure?

**Comment by cdietrich** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by cdietrich** [comment]
Jenkins Test

**Comment by cdietrich** [comment]
Jenkins test

**Comment by svenefftinge** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by cdietrich** [comment]
please review

**Comment by svenefftinge** [comment]
looks good

**Pull request merged**
