### PR TITLE
491411: Generated generator.Main uses createFileURI

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=491411
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

### CODE REVIEW

**Comment by svenefftinge** [comment]
:+1:

**Comment by svenefftinge** [comment]
You should be able to merge yourself now :) That said it's still good to wait for at least one review, especially when the code is more involved.

**Comment by LorenzoBettini** [comment]
OK, I go on with merging then, since you already reviewed that? Or should I run at least a jenkins test?

For sure, I'll always wait for at least one review in the future :)

**Comment by svenefftinge** [comment]
Yes, running at least "Jenkins test" is a good idea. And then merge yourself, yes.

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by LorenzoBettini** [comment]
The build failed, but having a look at that, the failure is due to 2 new warnings over the threshold configured for that job.  The warnings are not introduced by this PR, they were introduced, if I understand correctly, from this PR https://github.com/eclipse/xtext/pull/968 so I'd go on with merging.

**Comment by dhuebner** [comment]
@svenefftinge  @LorenzoBettini  I'm okay with ignoring the failed build due to the warnings introduced by an other PR. Otherwise, we need to clean up the already merged code and rebase this PR

**Pull request merged**
