### PR TITLE
AFC library

### PR DESCRIPTION
**Pull request by gallandarakhneorg**
Signed-off-by: Stéphane Galland <galland@arakhne.org>

### CODE REVIEW

**Comment by svenefftinge** [comment]
Hi Stephan could you redo the PR against maintenance?

**Comment by gallandarakhneorg** [comment]
Dear Sven.
Could you provide me the name of the repository where the Xtext website is located. I did not find it in the new set of xtext-* repositories?
Thank you.

**Comment by svenefftinge** [comment]
It this repository maintenance branch : https://github.com/eclipse/xtext/edit/maintenance/xtext-website/community.html
You end up there if you click the link on the website, that says "Add Your Project".

**Comment by gallandarakhneorg** [comment]
Thank you. I will request on the maintenance branch.

**Pull request closed without merging**
