### PR TITLE
Update all bundle requirements to 2.35.0

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by cdietrich** [comment]
can or should we teach this the set version script?

**Review by LorenzoBettini — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
@cdietrich I seem to remember that @szarnekow had already created a script or Java file to update the versions.

**Comment by cdietrich** [comment]
Yes but it’s not called from the script in the builds.md

**Comment by szarnekow** [comment]
@cdietrich I updated the script. Can you try to run it on linux?

**Comment by szarnekow** [comment]
> @cdietrich I seem to remember that @szarnekow had already created a script or Java file to update the versions.

It's not self-contained so a bit hard to use from here. For the time being, I opted for updating the shell script.

**Comment by cdietrich** [comment]
@szarnekow will do later today/this week

**Comment by szarnekow** [comment]
> @szarnekow will do later today/this week

I merged it for the time being. If it does no longer work on Linux, we can fix it in a subsequent PR.

**Comment by cdietrich** [comment]
seems to work good. no subsequent change needed

**Pull request merged**
