### PR TITLE
Bug 471239 - [formatter/xbase] format cast and postfix expressions

### PR DESCRIPTION
**Pull request by LorenzoBettini**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471239

**Comment by meysholdt** [comment]
Jenkins test

**Comment by LorenzoBettini** [comment]
By the way, in the Jenkins job that started, https://xtext-builds.itemis.de/jenkins/job/xtext-pull-request-verifier/565/consoleFull, I don't see any trace of the two tests I added... am I missing something?

**Comment by svenefftinge** [comment]
You forgot to check-in the generated java source :-)

**Comment by LorenzoBettini** [comment]
Oooopsss O:)
I checked it in now (including other Java files that have been regenerated due to the additional dispatch methods).

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by LorenzoBettini** [comment]
The Jenkins job failed, but I don't think that's related to this patch: I see all jobs have been failing lately...

**Comment by dhuebner** [comment]
Jenkins test

**Comment by meysholdt** [comment]
merged. Thank you for the contribution, Lorenzo :)

**Comment by meysholdt** [comment]
cherry-picked for 'maintenance' in #317

**Comment by LorenzoBettini** [comment]
My pleasure :)

**Pull request merged**
