### PR TITLE
[263773] First shot at parser rule fragments and super call

### PR DESCRIPTION
**Pull request by szarnekow**
Work in progress. Please do not merge.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=263773

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins test

**Pull request closed without merging**
