### PR TITLE
Updated IDEA version and fixed a issues in tests

### PR DESCRIPTION
**Pull request by szarnekow**
- Do not save editors reentrantly in tests
- Don’t use String.getBytes without encoding
- Adjustments to use VfsUtil.createIfMissing

### CODE REVIEW

**Comment by szarnekow** [comment]
This PR has still 5 failing tests cases in IDEA. There seems to be a problem with our PSI since we cannot find elements with SmartPsiPointers in some cases

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins test

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins test

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
