### PR TITLE
Remove obsolete packrat parser implementation

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by szarnekow** [comment]
@cdietrich What do you think? Feel like getting rid of some dead code?

**Comment by LorenzoBettini** [comment]
Closing and reopening to see whether it succeeds now that https://github.com/eclipse/xtext/pull/2938 has been merged

**Comment by LorenzoBettini** [comment]
are we going to merge this now that 2.34 has been released?

**Comment by szarnekow** [comment]
Yes, that's the plan, if nobody objects.

**Pull request merged**
