### PR TITLE
[480445] Added TypeReference#guessTypeRef

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=480445

**Comment by oehme** [comment]
Something is wrong here, the grammar flattener commit is already on master.

**Comment by szarnekow** [comment]
Nothing serious. I just branched from another branch to make the first thing available sooner.

**Comment by oehme** [comment]
Yeah but the diff in this PR is showing the same changes that are already on master, as if it was comparing with some older state. Pretty weird.

**Pull request merged**
