### PR TITLE
[492072] verbose generation for (i.e. get/set) method calls see https…

### PR DESCRIPTION
**Pull request by holgerschill**
…://bugs.eclipse.org/bugs/show_bug.cgi?id=492072

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=492072

**Comment by holgerschill** [comment]
jenkins test

**Comment by holgerschill** [comment]
The Test org.eclipse.xtend.ide.tests.contentassist.DataContentAssistTest.testDataAnnotation() does not ail locally and is maked as Flaky

**Comment by holgerschill** [comment]
Jenkins test

**Comment by holgerschill** [comment]
jenkins xtend-runtime-tests-java8-master-latest

**Comment by holgerschill** [comment]
Jenkins xtend-runtime-tests-master-latest

**Comment by holgerschill** [comment]
Please review

**Comment by holgerschill** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by holgerschill** [comment]
jenkins xtend-ide-tests-maintenance-latest

**Comment by akosyakov** [comment]
@holgerschill it is too late for 2.10, we will review it after the release, focusing on testing right now.

**Comment by holgerschill** [comment]
@akosyakov No problem. It was not my intention to have it merged for 2.10.

**Comment by kthoms** [comment]
This PR became invalid due to the repository split.

Adopted the changes into these PRs:
https://github.com/eclipse/xtext-extras/pull/42
https://github.com/eclipse/xtext-xtend/pull/28

This PR can be closed.

**Pull request closed without merging**
