### PR TITLE
Instantiate ClassFileReader via reflection

### LINKED ISSUE #3089: Fix api breakage with newest jdt
05:09:28  [ERROR] The method read(byte[], String) in the type ClassFileReader is not applicable for the arguments (InputStream, String)

Cc @iloveeclipse is this an intentional change upstream

### PR DESCRIPTION
**Pull request by cdietrich**
Fixes #3089

### CODE REVIEW

**Comment by cdietrich** [comment]
problems

- new jdt maven wont be published before the Xtext release
- likely newer platform artifacts will even require java 21 to run.

=> we would have to drop out from 2024-09 or explode there and or set minimal version to 21
i dont know what the exact plans there are though

**Comment by cdietrich** [comment]
@LorenzoBettini where would the parkplatz for this utility be

**Comment by cdietrich** [comment]
but xbase.testing does not depend to does it?

**Comment by LorenzoBettini** [comment]
I would go with the project that uses JDT internals, which are used by both projects involved in this PR, and move that utility method there; I don't have an Xtext workspace at the moment.

In any case, I can work on that later or in the near future without blocking this PR.

**Comment by cdietrich** [comment]
lets see what @szarnekow says

**Comment by szarnekow** [comment]
I would land this here. It’s unfortunate that JDT breaks in such a simple way but there’s not much we can do about that. Subsequently we could perform a systematic refactoring to extract code into a new bundle. That won’t help with old versions though. Same as this PR does only help for future versions

**Comment by LorenzoBettini** [comment]
@cdietrich so shall we merge this?

**Pull request merged**
