### PR TITLE
Follow-up on #746 (generator fixes)

### PR DESCRIPTION
**Pull request by sailingKieler**
* Changed Naming of gen scope provider class as suggested in review of #746,
* updated Naming of gen validators and gen proposal providers,
* introduced surrogate quickfix provider in case no stubs are created,

* change in content assist grammar generation in case of separated grammars
  (line of code that appears to be superfluous but did not harm)

### CODE REVIEW

**Comment by sailingKieler** [comment]
Jenkins test

**Comment by sailingKieler** [comment]
Jenkins test

**Comment by szarnekow** [comment]
:+1:

**Comment by sailingKieler** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by sailingKieler** [comment]
Jenkins xtend-runtime-tests-master-latest

**Comment by sailingKieler** [comment]
xtext-ide-tests-master-latest

**Comment by sailingKieler** [comment]
xtend-ide-tests-master-latest

**Comment by sailingKieler** [comment]
Jenkins xtend-ide-tests-master-latest

**Pull request merged**
