### PR TITLE
[idea][bug 475120] don't throw NPE for a psi element without an associated virtual file, e.g. PsiDirectory

### PR DESCRIPTION
**Pull request by akosyakov**
Change-Id: I70b24538cd241dfef4417a65b66543ac0e94902a
Signed-off-by: akosyakov <anton.kosyakov@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=475120

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins test

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
