### PR TITLE
[472120] IllegalArgumentException in WildcardTypeReference.addUpperBound

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=472210

**Comment by szarnekow** [comment]
Jenkins test

**Comment by jdeyton** [comment]
FYI, this pull request was associated with the incorrect bug ticket 472210.

**Comment by szarnekow** [comment]
My bad, I put the wrong bug id into the subject

**Pull request merged**
