### PR TITLE
Fix PositionReader wrong position on files with carriage returns

### PR DESCRIPTION
**Pull request by jnt0r**
This fixes the issue #2715 in the PositionReader on wrong position returned on files containing carriage returns.

As I said, I'm still not 100% sure this is the best solution. I'm open for input and new ideas.

### CODE REVIEW

**Comment by joaodinissf** [comment]
Hi jnt0r! I also ran into issue #2715 this week, and happened to look into this problem independently. I just saw that you had reported the same issue and prepared a PR for it.

The fix I prepared changes the behavior of the `read()` function so that it doesn't skip '\r' characters. I think this gets at the root cause of the issue. I have created a PR with it, #2735.

I believe that this is a more robust solution than the one you implemented in this change, because of what you mention in [this comment](https://github.com/eclipse/xtext/issues/2715#issuecomment-1614956679). What do you think?

**Comment by szarnekow** [comment]
I prefer getting rid of the LineNumberReader altogether, too.
@joaodinissf can you please add tests to your PR with Linux/ Windows and mixed line endings?

**Comment by joaodinissf** [comment]
Will do, @szarnekow.

**Comment by szarnekow** [comment]
Bonus points if you can make it work with the anachronistic `\r` only (not `\r\n`), too.

**Comment by joaodinissf** [comment]
@szarnekow, since @jnt0r already had some work preparing this contribution, how do you feel about the following plan:

1. We merge #2735 with the fix.
2. We merge #2734 with the tests that @jnt0r prepared.
3. In a separate PR, I can add a few more tests and make any necessary adjustments to correctly handle the bonus issue that you correctly [identified](https://github.com/eclipse/xtext/pull/2734#issuecomment-1625129094).

That way, both @jnt0r's and my contributions and efforts are preserved. How does that sound?

**Comment by szarnekow** [comment]
Sounds very good to me.

**Comment by jnt0r** [comment]
@joaodinissf I will take a look at your PR. Getting rid of the LineNumberReader sounds like a more appropriate solution that I didn't want to do :)

**Comment by jnt0r** [comment]
@joaodinissf your solution looks good to me. Also tested it with the test case I provided. I will close this PR as your solution is more appropriate.

**Pull request closed without merging**
