### PR TITLE
[488589] Fix NPE in ReferenceFinder.findLocalReferencesFromElement

### PR DESCRIPTION
**Pull request by asheiduk**
Solves https://bugs.eclipse.org/bugs/show_bug.cgi?id=488589

Signed-off-by: Andreas Heiduk <asheiduk@gmail.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488589

**Comment by svenefftinge** [comment]
Do you want to close this and do another against 'maintenance'?

**Comment by asheiduk** [comment]
@svenefftinge Oh, good you mention it, "maintenance" would be *much* better for me indeed.

**Comment by asheiduk** [comment]
Sorry for nor reading your comment completely.

**Pull request closed without merging**
