### PR TITLE
Add GTSMorpher project to list of Xtext-projects

### PR DESCRIPTION
**Pull request by szschaler**
I've added a description of my GTSMorpher language to the list of projects.

### CODE REVIEW

**Comment by szschaler** [comment]
I used to have an ECA, but this seems to have disappeared, together with my Eclipse account. Have just created a new one...

**Comment by cdietrich** [comment]
@szschaler please note: the eca thing is also not working with edits from github unfortunately (i am sorry for tha and hope the eclipse webmasters get this resolved one day). thus you may have to sign-off the commit from a local machine

**Comment by szschaler** [comment]
@cdietrich heard and understood. Will try and get to this asap.

**Comment by szschaler** [comment]
I think I have now correctly rewritten the commit message to include the sign off. Check is still failing, but I'm not quite sure why. @cdietrich any ideas?

**Comment by cdietrich** [comment]
the problem is that the user in the commit is still
Steffen Zschaler (szschaler@****.noreply) == pseudo-user for your github.

**Comment by cdietrich** [comment]
i think the easiest would to create a new branch/commit+pr from a local branch and/or force-push it to this branch

**Comment by miklossy** [comment]
@szschaler : Thanks for your PR! If it is easier for you, feel free to close this PR and I will create a new one with the same change.

**Comment by szschaler** [comment]
@cdietrich thanks: I missed that. @miklossy if you can do this easily, then it would save me some hassle. But please do let me know if it is too much hassle for you and I will set up a new PR. Many thanks!

**Pull request closed without merging**
