### PR TITLE
Issue 2235 - Update to Jetty 11

### PR DESCRIPTION
**Pull request by florianpirchner**
Hi Christian,

i signed the contributor agreement and happy to provide you with this pull request.

Best, Flo

### CODE REVIEW

**Comment by cdietrich** [comment]
thx @florianpirchner 
i miss a change to
org.eclipse.xtext.xtext.wizard.WebProjectDescriptor
which still refers to old jetty and slf4j
(start runtime eclipse, choose new xtext project, select web + build system maven or gradle)

**Comment by florianpirchner** [comment]
@cdietrich - i am not sure, why continuous-integration/jenkins/pr-head cannot be built. Found no further information in build.

Best, Flo

**Comment by cdietrich** [comment]
There were changes in orbit. You need to rebase on this mornings change on main branch

**Comment by florianpirchner** [comment]
I rebased the commits in a new branch. Is there a way to change the branch in this PR? Or should i create new PR?

Sorry, my first time using PR and google says many different things about best practice.

Best Florian

**Comment by cdietrich** [comment]
Guess you have to force push on this branch. Or simply open new pr

**Comment by florianpirchner** [comment]
@cdietrich hi christian, new PR is https://github.com/eclipse/xtext/pull/2763.

Hope i did everything fine :)

Best Flo

**Pull request closed without merging**
