### PR TITLE
[263773] Parameterized rule support in content assist parser

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=263773

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-master-latest

**Pull request merged**
