### PR TITLE
[471384] Do not wait for auto build in tests

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471384

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-slow-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins xtext-slow-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtext-runtime-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtend-slow-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtend-runtime-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtend-ide-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtend-ide-tests-maintenance-latest

**Pull request closed without merging**
