### PR TITLE
[490871]  Reverted previous change and applied a more local fix

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=490871

**Comment by svenefftinge** [comment]
Much better, thank you!

**Comment by cdietrich** [comment]
Jenkins xtend-ide-tests-master-latest

**Comment by cdietrich** [comment]
Jenkins test

**Pull request merged**
