### PR TITLE
Remove obsolete compiler option assignments

### PR DESCRIPTION
**Pull request by mehmet-karaman**
This should fix the compilation errors caused by removed CompilerOptions in Jdt.

### CODE REVIEW

**Comment by cdietrich** [comment]
Which is the minimal jdt version 
This removal requires 
Last time we needed to use reflection

**Comment by cdietrich** [comment]
@mehmet-karaman can we check if there is more stuff that is marked for removal and is in @iloveeclipse delete queue

**Comment by mehmet-karaman** [comment]
oo .. You're right.. I guess currently it compiles against the latest jdt... but it has to be conform until 2022-03, right?

**Comment by cdietrich** [comment]
Yes. Depending if the team finds time to work on the j17 minimum story

**Comment by mehmet-karaman** [comment]
Are there tests which are running on 2022-03? How we can recognize if we break something on older platform versions?

**Comment by cdietrich** [comment]
yes the one on ci.eclipse.org/xtext (continuous-integration/jenkins/pr-head)

**Comment by cdietrich** [comment]
but am not sure how good overage is.

**Comment by LorenzoBettini** [comment]
What does that field mean? Is in general only setting the sourceLevel, without the originalSourceLevel enough (even in the past)?

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/xtext/job/PR-3206/1/

Ton of test fails

**Comment by LorenzoBettini** [comment]
> https://ci.eclipse.org/xtext/job/xtext/job/PR-3206/1/
> 
> Ton of test fails

OK, I see.

Another good candidate to be inserted here https://github.com/eclipse/xtext/pull/3204 ;)

**Comment by mehmet-karaman** [comment]
I've contacted Andrey and srikant and they've said that it is obsolete since version 4.33 .. So for all versions before 4.33 we have to do the reflective workaround. I've also asked if there are any CompilerOptions planned for removal, he said that nothing is left. 

He also added that @cdietrich did similar workarounds for something with JSR .. The same has to be done in this case

**Comment by mehmet-karaman** [comment]
I've found the PR which mentions something with JSR .. I am going to mimik this for the two compiler options.. 

https://github.com/eclipse/xtext/pull/3189

**Comment by cdietrich** [comment]
@mehmet-karaman please note we had to rewrite that one 5 times.
please do the same as its currently on main.
see the 

```
if (INLINE_JSR_BYTECODE != null) {
			try {
				INLINE_JSR_BYTECODE.invoke(this.compilerOptions, true);
			} catch (Throwable e) {
				// ignore
			}
		}
```

**Comment by mehmet-karaman** [comment]
Just a sidenote:
While checking the occurences, I've seen that JDT marked the following constant as deprecated: 
JavaCore.COMPILER_CODEGEN_INLINE_JSR_BYTECODE

Might be we also get problems with that in the future..

**Review by cdietrich — APPROVED** [review]

**Comment by mehmet-karaman** [comment]
@cdietrich is this build ok now? Changed the state of this PR from draft to open..

**Comment by cdietrich** [comment]
Will check when Jenkins is though and I am back from lunch nd meeting

**Comment by mehmet-karaman** [comment]
:) finally all green

**Comment by cdietrich** [comment]
thx @mehmet-karaman can you rebase the other one

**Pull request merged**
