### PR TITLE
fix jetty inconsistency

### PR DESCRIPTION
**Pull request by cdietrich**
fix jetty inconsistency

### CODE REVIEW

**Review by LorenzoBettini — COMMENTED** [review]
Maybe we could use a property in the POM and refer to the property in the dependencies.
This should improve consistency.

**Comment by cdietrich** [comment]
the inconsistency is not between poms or within pom
but the bump from gradle got missing

**Comment by LorenzoBettini** [comment]
> the inconsistency is not between poms or within pom but the bump from gradle got missing

Yes, I understand, but for future updates, changing only the value of the property will be easier. That's what I was proposing.

**Comment by cdietrich** [comment]
feel free to provide a 2nd pr

**Comment by LorenzoBettini** [comment]
@cdietrich if you don't mind I added a commit on top of this PR

**Pull request merged**
