### PR TITLE
[480686] Fixed regression in NodeModelBuilder

### PR DESCRIPTION
**Pull request by szarnekow**
For some patterns in the grammar it may have happend that a root node
without a grammar element was produced.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=480686

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins smoke-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins test

**Pull request merged**
