### PR TITLE
[idea] Added guard for NPE in PhpStorm Bug 483095

### PR DESCRIPTION
**Pull request by dhuebner**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=483095
Signed-off-by: Dennis Huebner <dennis.huebner@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=483095

**Comment by dhuebner** [comment]
Jenkins intellij-tests-master-latest

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins intellij-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins test

**Comment by oehme** [comment]
Jenkins test

**Comment by dhuebner** [comment]
Tested locally on my machine

**Pull request merged**
