### PR TITLE
470586: FIX useless if check for the first switch's case

### PR DESCRIPTION
**Pull request by LorenzoBettini**
This fixes a problem I introduced in the previous PR, https://github.com/eclipse/xtext/pull/987

The second commit also regenerates all the Xtend files.

### CODE REVIEW

**Comment by dhuebner** [comment]
@LorenzoBettini  My be also interesting to run these tests before PR merge:
https://xtext-builds.itemis.de/jenkins/view/All/job/xtext-ide-tests-master-oldest/910/

**Comment by LorenzoBettini** [comment]
Done.

**Comment by svenefftinge** [comment]
Jenkins xtend-runtime-tests-java8-master-latest

**Comment by svenefftinge** [comment]
Jenkins xtext-ide-tests-master-oldest

**Pull request merged**
