### PR TITLE
[506146] Fixed Typo in Docs

### PR DESCRIPTION
**Pull request by cdietrich**
[506146] Fixed Typo in Docs

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=506146

**Comment by cdietrich** [comment]
please review

**Comment by dhuebner** [comment]
+1

**Comment by nbhusare** [comment]
+1

**Pull request merged**
