### PR TITLE
Update community.html to add ASSIST tool suite

### PR DESCRIPTION
**Pull request by RobertHilbrich**

### CODE REVIEW

**Comment by cdietrich** [comment]
@RobertHilbrich can you please sing-off the commit

**Comment by cdietrich** [comment]
Let us know if the signoff stuff is too complicated
@miklossy could also redo the pr

**Comment by RobertHilbrich** [comment]
Hm - any easy way to fix that? Or do I have to do the pr again?

**Comment by cdietrich** [comment]
I am not aware that it can be done in the web interface
So you would have to clone. Checkout branch. Amend. Force push

@eclipsewebmaster @waynebeaton is there any news on getting simple web PR done without all that Klimbim?

**Comment by RobertHilbrich** [comment]
@miklossy Could you please redo my PR - this seems too much hassle for 5 lines of html code to be added

**Comment by waynebeaton** [comment]
> @eclipsewebmaster @waynebeaton is there any news on getting simple web PR done without all that Klimbim?

I'm not sure what Klimbim is, but I assume that you mean activity that you feel is unnecessary or extraneous. The contribution process is well-defined. Raise specific requests for change in Bugzilla. (e.g., [Bug 558653](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558653)).

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=558653 is what i was looking for

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext/pull/1792

**Pull request closed without merging**
