### PR TITLE
Migrate xtext web to jakarta - squashed commits

### PR DESCRIPTION
**Pull request by florianpirchner**
Squashed the commits.
Signed-off-by: Florian Pirchner <florian.pirchner@gmail.com>

### CODE REVIEW

**Comment by florianpirchner** [comment]
Hi Christian,
the new PR wir squashed commits.

Best Flo

**Review by cdietrich — APPROVED** [review]

**Comment by cdietrich** [comment]
thx @florianpirchner

**Comment by realdavidvega** [comment]
Hi everyone involved in this project, first of all thanks for the amazing work being done here. 

I'm part of a team working on a Xtext project and actually to have this would be important to us, as we would need to integrate the servlet on a Spring Boot application with Jakarta instead of Javax.

Do you know if this would be part of `Release_2.32`? Thanks.

**Comment by cdietrich** [comment]
Yes it will be

**Comment by cdietrich** [comment]
@realdavidvega would be nice if you could give 2.32.0.M2 a try and give feedback

**Pull request merged**
