### PR TITLE
align junit5 in target platforms with eclipse jdts

### PR DESCRIPTION
**Pull request by cdietrich**
align junit5 in target platforms with eclipse jdts

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
Argh! Now tycho surefire does not see the JUnit 5 tests :'(

**Comment by LorenzoBettini** [comment]
Maybe this might help https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/test-mojo.html#providerHint

**Comment by cdietrich** [comment]
hmm with the hint
InjectionExtensionTest
still fails at least with r202203

**Comment by LorenzoBettini** [comment]
> hmm with the hint InjectionExtensionTest still fails at least with r202203
> 
> wonder if we should use maven-surefire

You mean it fails with r202303 right? I see it fail on GitHub Actions.

I don't find `InjectionExtensionTest`

**Comment by cdietrich** [comment]
/org.eclipse.xtext.testing.junit5.tests/src/org/eclipse/xtext/testing/tests/junit5/InjectionExtensionTest.java
@LorenzoBettini shall i push the config of the hint?

**Comment by LorenzoBettini** [comment]
yes, please

**Comment by cdietrich** [comment]
@LorenzoBettini pushed

**Comment by LorenzoBettini** [comment]
> hmm with the hint InjectionExtensionTest still fails at least with r202203
> 
> wonder if we should use maven-surefire

I can reproduce the problem locally... I'll try to switch to maven-surefire

**Comment by cdietrich** [comment]
thx. seems to work now

**Review by LorenzoBettini — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
@cdietrich yes!

**Pull request merged**
