### PR TITLE
[430767] Documentation of Template Comments

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=430767

**Comment by cdietrich** [comment]
@kthoms please review

**Comment by cdietrich** [comment]
bildschirmfoto 2017-03-02 um 17 45 34

**Comment by kthoms** [comment]
👍

**Pull request merged**
