### PR TITLE
[493900] fixed array list literal handling in xbase compiler

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=93900

**Comment by LorenzoBettini** [comment]
@cdietrich I think the bug reference is wrong

**Comment by cdietrich** [comment]
yes seems there got a number left

**Comment by cdietrich** [comment]
Jenkins test

**Comment by dhuebner** [comment]
Jenkins test

**Comment by dhuebner** [comment]
Jenkins test

**Comment by cdietrich** [comment]
Jenkins test

**Pull request closed without merging**
