### PR TITLE
Xtext website: Fix broken html rendering due to whitespace changes.

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by miklossy** [comment]
The rendering of the https://www.eclipse.org/Xtext/documentation/104_jvmdomainmodel.html website is currently broken:
screenshot

This PR tries to fix this.

**Comment by kthoms** [comment]
Could you elaborate what "tries" means? Have you regenerated the page? Could you add a screenshot?

We could try that, it at least won't break anything.

**Comment by cdietrich** [comment]
i assume there are some eclipse webservers serving old stuff.
also corporate proxies might cache that old stuff.

**Comment by miklossy** [comment]
@kthoms I regenerated the website lokally using Jekill and it looks good:
image

**Pull request merged**
