### PR TITLE
Simple typo corrected

### PR DESCRIPTION
**Pull request by Bien-CV**

### CODE REVIEW

**Comment by kthoms** [comment]
@Bien-CV Thanks for your contribution. Unfortunately, although that trivial, [contributing](https://github.com/eclipse/xtext/blob/master/CONTRIBUTING.md) would require some additional work. Specifically it require that you sign a [Contributor Agreement](https://www.eclipse.org/legal/ECA.php) and that you sign-off the commit.

If it is OK for you, I would just fix the docs myself and close this PR.

**Comment by Bien-CV** [comment]
You're welcome.

Please do so, I didn't notice this was an Eclipse repository and wasn't
aware of the requirements.

2017-12-20 15:11 GMT+01:00 Karsten Thoms <notifications@github.com>:

**Comment by kthoms** [comment]
Fixed with #c4a825c8f1a519d06136846f7c29b9ab27d3f73e

**Comment by kthoms** [comment]
Thanks @Bien-CV

**Pull request closed without merging**
