### PR TITLE
[#2625] prepare Jenkinsfile and Scripts for release builds

### PR DESCRIPTION
**Pull request by cdietrich**
[#2625] prepare Jenkinsfile and Scripts for release builds

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini please do so.
if you have a staging plugin,
and we have a archivedP2 version,
we can use it in 

xtext-reference-projects/greetings-(gradle/maven/tycho)-2.31.0(-J11)? pom/build.gradle/target and xtext-reference-projects/domainmodel/2.31.0/ similar to
https://github.com/itemis/xtext-reference-projects/compare/cd_m0

(adopting integrationtests target wont work)

**Comment by LorenzoBettini** [comment]
> xtext-reference-projects/greetings-(gradle/maven/tycho)-2.31.0(-J11)? pom/build.gradle/target and xtext-reference-projects/domainmodel/2.31.0/ similar to https://github.com/itemis/xtext-reference-projects/compare/cd_m0
> 
> (adopting integrationtests target wont work)

I don't understand this part

**Comment by cdietrich** [comment]
am not sure what is unclear?!?

adapt the poms/build.gradle to use 2.31.0 relase version and the staging repo
adapt the targets to use the p2 repo archived by the job.
dont adapt the integ tests

**Comment by LorenzoBettini** [comment]
Aren't the integration tests the same thing as the reference projects?

**Comment by cdietrich** [comment]
In the reference projects project there is a integtest project that calls the wizards and examples via swtbot. This part won’t work cause maven stuff is not on central and update site is not published

**Comment by cdietrich** [comment]
@LorenzoBettini any update here?

**Comment by cdietrich** [comment]
i have: https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-release/
but you need to double check if branch is correct

**Comment by LorenzoBettini** [comment]
OK

**Comment by cdietrich** [comment]
@LorenzoBettini as RC1 / release is approaching: any update here?

**Comment by LorenzoBettini** [comment]
@cdietrich I've just run the dry-run, you can find the p2 update site here https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-release/lastSuccessfulBuild/artifact/build/

The composite metadata look fine: https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-release/lastSuccessfulBuild/artifact/org.eclipse.xtext.p2repository/target/checkout/

I closed the staging Maven repositories for Xtext and Xtend, which should be consumable in a minute.

**Comment by cdietrich** [comment]
https://github.com/itemis/xtext-reference-projects/compare/cd_releasetest

**Comment by cdietrich** [comment]
https://github.com/itemis/xtext-reference-projects/actions/runs/5067962959 looks promising

**Comment by LorenzoBettini** [comment]
> https://github.com/itemis/xtext-reference-projects/actions/runs/5067962959 looks promising

There's a failure in a few jobs, but maybe they're not configured correctly?

**Comment by LorenzoBettini** [comment]
https://github.com/itemis/xtext-reference-projects/actions/runs/5067907975

**Comment by cdietrich** [comment]
this is a run where i messed up the repo list update. only the latest 4 count

**Comment by LorenzoBettini** [comment]
> are we good to merge? from my pov we are.

Yes!

We should then change the branch in the job, and move the job into the "Xtext Releases" view

**Comment by cdietrich** [comment]
hmm dont know how the views are configured

**Comment by LorenzoBettini** [comment]
I'll try to figure it out

**Pull request merged**
