### PR TITLE
[471384] A few tests depend on auto building

### PR DESCRIPTION
**Pull request by szarnekow**
They fail with an explicit build request. To be analysed 
in 2.9 branch

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471384

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtend-ide-tests-maintenance-latest

**Comment by szarnekow** [comment]
Jenkins xtext-ide-tests-maintenance-latest

**Pull request merged**
