### PR TITLE
[2909] xtext.logging versionRange 0.0.0 in extraRequirements

### LINKED ISSUE #2909: Inconsistent major version change for org.eclipse.xtext.logging
org.eclipse.xtext.logging has for a long time been version 1.x, but the latest 2.34 build changes it to 2.x which is superficially sensible given that all other xtext plugins are 2.x. However this is a violation of https://wiki.eclipse.org/Version_Numbering 

If a breaking change is really required Xtext must go to 3.x, else please revert the common sense typo and stay at 1.x.

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #2909

### CODE REVIEW

**Review by szarnekow — APPROVED** [review]
Code looks good. Let's wait for Jenkins. Will you also update the reference projects?

**Comment by LorenzoBettini** [comment]
@szarnekow what should I do with the reference projects? If I understand correctly I should first create a new nightly p2 site and then try to run their workflows manually?

**Comment by cdietrich** [comment]
merge this one. wait for deploy to finish. pr reference projects

**Comment by LorenzoBettini** [comment]
> merge this one. wait for deploy to finish. pr reference projects

@cdietrich what do you mean by "pr reference projects"?

"deploy": are the projects going to use this one https://ci.eclipse.org/xtext/job/xtext/job/main/lastSuccessfulBuild/artifact/build/p2-repository/?

**Comment by cdietrich** [comment]
create a new branch.
import into xtext dev eclipse
run the all launch script.
manually update the domain model
commit the changes.
open pr.

**Comment by cdietrich** [comment]
and no once main run. the nightly deploy job will run on jenkins

**Comment by LorenzoBettini** [comment]
@cdietrich let's see whether I understood correctly :)
https://github.com/xtext/xtext-reference-projects/pull/401

Maybe it's worthwhile to document this procedure?

**Comment by LorenzoBettini** [comment]
@cdietrich, the failure is the same, so I'm afraid I don't understand how to consume my fix merged on master...

**Comment by cdietrich** [comment]
i assume either eclipse or github do wired caching
=> just retry some time later

**Comment by cdietrich** [comment]
@LorenzoBettini did you forget to update this one:
https://github.com/eclipse/xtext/blob/8f1972148435c3bb9836282eec53e18d739659d7/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml#L107

**Comment by LorenzoBettini** [comment]
> <versionRange>${xtextVersion}

Sorry, I had missed that one :(
I committed it now directly on `main` https://github.com/eclipse/xtext/commit/4eaa306d49576c79e2b3e8b8a483cf426e9ba873

**Comment by cdietrich** [comment]
Ok

**Comment by LorenzoBettini** [comment]
> i assume either eclipse or github do wired caching => just retry some time later

@cdietrich 
Sorry if I insist on this, but the log (https://pipelinesghubeus23.actions.githubusercontent.com/VGbhG7MqInqDfxY0bKv0qAuPeX3d22owq0UvtAsHMpYjQuu8bd/_apis/pipelines/1/runs/7181/signedlogcontent/2?urlExpires=2024-01-15T17%3A37%3A09.8204863Z&urlSigningMethod=HMACV1&urlSignature=f9iHreszdMpxljuBpbtaqqVOoE1ZXrYVW%2BowSiXD7O4%3D) shows this:

```
[INFO] Resolving class path of org.eclipse.xtext.swtbot.testing...
[INFO] Fetching org.eclipse.xtext.logging_2.34.0.v20240115-1416.jar from https://download.eclipse.org/modeling/tmf/xtext/updates/nightly/plugins/ (14.36kB)
```

So the fixed version of Xtext wizard corresponding to this PR must be deployed on the nightly update site before the reference projects build successfully (see my previous questions); or again am I missing something?

**Comment by cdietrich** [comment]
Maybe two jobs racing against each other? Deploy of Xtext and the reference project job?

**Comment by cdietrich** [comment]
And yes the nightly deploy job needs to run first 
Checking on mobile is terrible so can’t look right now

**Comment by cdietrich** [comment]
I don’t know how this works 
Thought you configured to run as follow up of main job

**Comment by LorenzoBettini** [comment]
@cdietrich Yes, you're right! I can see in Jenkins nightly job

```
originally caused by:
   Branch indexing
```

I totally forgot about that! Sorry.

**Pull request merged**
