### PR TITLE
[#1086] Move releng projects to xtext-umbrella

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
Before this PR can be applied https://github.com/eclipse/xtext-umbrella/pull/7 has to be merged build jobs have to be updated to use the new location.

**Comment by dhuebner** [comment]
Could you also remove the .DS_Store file?
+1

**Comment by kthoms** [comment]
The .DS_Store file is ignored in umbrella anyway

**Comment by kthoms** [comment]
Ah, it is still present. Just a second, will update the PR.

**Comment by spoenemann** [comment]
Oh sorry, I haven't noticed this PR. Already removed the releng subfolder and Jenkinsfile.

**Comment by kthoms** [comment]
NP, result is the same ;)

**Pull request closed without merging**
