### PR TITLE
Bump 2.38 and bootstrap xtend-maven-plugin

### PR DESCRIPTION
**Pull request by LorenzoBettini**

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini thought we want to bring in your pr first?
or will this be no problem?

**Comment by LorenzoBettini** [comment]
@cdietrich I had already rebased my PR on top of the released main, and solved the conflicts due to the new MWE2.

I guess you're right: bringing my PR in first should save for further conflicts.

So let's postpone this; probably, it will be even easier to simply recreate this PR, since I used the fix version script after all.

**Comment by LorenzoBettini** [comment]
@cdietrich so shall we merge the Java 17 PR?

**Comment by cdietrich** [comment]
@LorenzoBettini are the open points addressed?

**Comment by LorenzoBettini** [comment]
@cdietrich I thought we'd address open points in the future. I seem to recall that there are no blocking open points. CC @szarnekow

**Comment by cdietrich** [comment]
future = as in a follow up or as "somewhen in 2027"

**Comment by cdietrich** [comment]
from my pov they should be adressed before the next release

**Comment by LorenzoBettini** [comment]
OK, can you please point me to the points that remain to be addressed? I'll see what I can do.
Or summarize them in the other PR.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/pull/3233#issuecomment-2473079813

**Comment by LorenzoBettini** [comment]
@cdietrich the PR has been updated with the Java 17 PR merged.

**Review by cdietrich — APPROVED** [review]

**Pull request merged**
