### PR TITLE
[471278]: Fixed NPE in xtend generator

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471278

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins test

**Comment by dhuebner** [comment]
The error is:
00:09:18.451 Error: file /opt/jenkins/home/workspace/xtext-pull-request-verifier/org.eclipse.xtext.git/plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/XtendGenerator.java, line 590: Type mismatch: cannot convert from IAppendable to ITreeAppendable

**Comment by szarnekow** [comment]
Jenkins test

**Comment by szarnekow** [comment]
Jenkins test

**Pull request merged**
