### PR TITLE
[idea] Clean up

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by svenefftinge** [comment]
Jenkins test

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
