### PR TITLE
Du bug472430

### PR DESCRIPTION
**Pull request by dhuebner**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=472430

**Comment by dhuebner** [comment]
Jenkins intellij-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins intellij-tests-master-latest

**Comment by dhuebner** [comment]
Jenkins intellij-tests-master-latest

**Pull request merged**
