### PR TITLE
attempt to fix upload

### PR DESCRIPTION
**Pull request by cdietrich**
cc @HannesWell

### CODE REVIEW

**Comment by cdietrich** [comment]
or do we also have to add a run id or something?

**Comment by cdietrich** [comment]
addd no there is a j17 and j21 build on linux

**Comment by HannesWell** [comment]
This could fix the problem, but I have to check (the references) in detail when back home.

**Comment by HannesWell** [comment]
I checked the existing workflows and there is either only have one job or use different names like here. So I think this fix is reasonable.
I just wonder why this didn't happen before, maybe because there were no failures?

Besides this, I think we also need https://github.com/eclipse/xtext/pull/3148 to make the test-publication work.

**Pull request merged**
