### PR TITLE
[bug 483931] Relativize output paths even for non existent folders

### PR DESCRIPTION
**Pull request by akosyakov**
Change-Id: Idce8fadc25afb9f70b81133d4b7bf6ccd6e0a667
Signed-off-by: akosyakov <anton.kosyakov@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=483931

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by svenefftinge** [comment]
:+1:

**Comment by svenefftinge** [comment]
it should be requested against maintenance

**Pull request closed without merging**
