### PR TITLE
some more defaults changed to java 17

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Review by LorenzoBettini — APPROVED** [review]
@cdietrich I hope you don't mind: I rebased your branch on top of the rebased branch of mine, in order to make the build green again with the merged default Java 21 PR.

If I understand correctly, this fixes the remaining points in the Java 17 PR, right?

**Comment by cdietrich** [comment]
yes

**Comment by LorenzoBettini** [comment]
OK, so can we now merge the Java 17 PR?

**Comment by cdietrich** [comment]
> OK, so can we now merge the Java 17 PR?

from my pov yes. @szarnekow wdyt?

**Pull request merged**
