### PR TITLE
 [439167] Use Monospace Font to view the generated code 

### PR DESCRIPTION
**Pull request by cdietrich**
…t symbolic name)

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=439167

**Comment by cdietrich** [comment]
Jenkins test

**Comment by akosyakov** [comment]
please merge

**Comment by akosyakov** [comment]
and close the corresponding bug if it is fixed

**Pull request merged**
