### PR TITLE
[#1095] Remove MWE2 documentation from the Xtext repository.

### PR DESCRIPTION
**Pull request by miklossy**
- The MWE2 documentation has already been transfered to the MWE2 GitHub
repository with the PR https://github.com/eclipse/mwe/pull/140

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by szarnekow** [comment]
Generally speaking it's bad practice to simply delete resources without establishing a permanent redirect. What is the reasoning behind this?

**Comment by miklossy** [comment]
Thanks for the hint @szarnekow ! The intention behind this was to clean up the Xtext documentation as much as possible. I do not prefer a permanent redirect since it would pollute the Xtext documentation folder. I would even remove the https://github.com/eclipse/xtext/blob/website-published/xtext-website/documentation/304_ide_concepts.html and https://github.com/eclipse/xtext/blob/website-published/xtext-website/documentation/310_web_integration.html pages to further clean up the Xtext documentation repository.

However, we should mention that in the release notes. People who will try to access to moved webpages can get in touch with us for further assistance.

@cdietrich What is your opinion about this?

**Comment by cdietrich** [comment]
i dont care. i would have kept it in the first place. i also dont know how to do a redirect

**Comment by cdietrich** [comment]
but it does not matter anyway as the old code whas just an html sitting around and referenced nowhere.
we did also do zero redirects for documentation moves and removals in the past

**Comment by cdietrich** [comment]
maybe we have place a html with a link to the new MD

**Pull request merged**
