### PR TITLE
[#2189] workaround for missing manifest

### PR DESCRIPTION
**Pull request by cdietrich**
[#2189] workaround for missing manifest

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini  is missing MANIFEST intentional?

**Comment by cdietrich** [comment]
alternative solution might be to configure workflow not to reproduce plugin.xml and no manifest
or create manifest

**Comment by cdietrich** [comment]
i also cannot run workflow
in /Users/cdietrich/xtext-main2/git/xtext/org.eclipse.xtext.common.types.tests
as mwe launch is not on classpath

@LorenzoBettini  what is the pattern to solve that?

**Comment by szarnekow** [comment]
Would we need a build-time dependency for that?

**Comment by cdietrich** [comment]
alternative approach

**Comment by cdietrich** [comment]
see 2nd pr. as it is a test project i think it does not matter.
but i did not test any other workflow if they run

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini is missing MANIFEST intentional?

Yes: that is a JAR packaging type project, with no PDE nature, whose tests are meant to be executed with maven surefire, NOT with tycho surefire.

**Comment by LorenzoBettini** [comment]
> i also cannot run workflow in /Users/cdietrich/xtext-main2/git/xtext/org.eclipse.xtext.common.types.tests as mwe launch is not on classpath
> 
> @LorenzoBettini what is the pattern to solve that? do we have this pattern somewhere else?

I think you figured it out here https://github.com/eclipse/xtext/pull/2191/files#diff-3b952e6aec6d75eff0a82a180180594f5f02f9b36a0312532364296e52080ba2R46 right?

As I said above, this is a pure Maven JAR project.

**Pull request closed without merging**
