### PR TITLE
Generate psiclass based on jvmderivedtype

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by oehme** [comment]
Jenkins test

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by akosyakov** [comment]
Jenkins intellij-tests-master-latest

**Comment by oehme** [comment]
Please rebase this on master to run the intellij tests. I had to make an adjustment to the Jenkins job, as we now also have the 'web' projects built with Gradle.

**Pull request closed without merging**
