### PR TITLE
another classgraph bump

### PR DESCRIPTION
**Pull request by cdietrich**
also using 0.0.0 as @merks keeps doing updates too often
(our 2.36 release is broken, but i wont have time for a hotfix) :(

### CODE REVIEW

**Comment by merks** [comment]
Sorry, I didn't consider that this might break something.  I could have tried to back out the changes but now Orbit is also released.  Sorry sorry.

**Comment by LorenzoBettini** [comment]
> also using 0.0.0 as @merks keeps doing updates too often (our 2.36 release is broken, but i wont have time for a hotfix) :(

What do you mean by broken? It cannot be installed?

**Comment by cdietrich** [comment]
no, the new xtext project wizard will produce a non working target platform

**Comment by mehmet-karaman** [comment]
> no, the new xtext project wizard will produce a non working target platform

Maybe there is a previous version of the orbit which we could refer?

**Comment by cdietrich** [comment]
For the release it does not matter
As the orbit url and the version is hard coded

**Comment by merks** [comment]
For future reference, the Platform's RC2 build is at offset -1 which means their contribution is Friday the week before everyone else contributes.  They do the build for that on Wednesday.  The Orbit, EMF, and ECF milestones are due Tuesday/today.  Given this is RC2/final, Orbit, EMF, ECF must (should) provide final content, i.e., release content.   To avoid last minute stress, the Orbit release build was done yesterday.  I could have backed out the version if I were informed sooner.  The update was done by this commit one week ago:

https://github.com/eclipse-orbit/orbit-simrel/commit/036cf7c7c42fdaf0f326a28ac9ce07078199b292

In general updates happen the day after something becomes available and updates generally continue until the Platform's RC2 week.

**Comment by cdietrich** [comment]
this basically destroys the relase flow we did the last 8 years.
we alwayst built releases at RC1

**Comment by merks** [comment]
Unfortunately I'm not aware of  every flow of every project.  It looks like the release was produced 2024-08-25 so if I'd produced Orbit milestones more rapidly toward the end of the release cycle, the Orbit change from 2024-08-21 would have been consumed by your build.  Live and learn.  

One could subscribe to the repo where the changes happen:

https://github.com/eclipse-orbit/orbit-simrel

One might do less hard coding, though I don't know if that's feasible.

One might time releases around Orbit releases if your release content depends on exact versions:

image

image

This pattern has been in place for quite some time.  I suppose the important change is that Obit updates are semi-automatic such that there typically changes right up until RC2, unless someone makes me aware of a change that is problematic so late in the cycle.

**Comment by cdietrich** [comment]
i guess we just need to live with stuff exploding.
or have other people than me building....

**Comment by LorenzoBettini** [comment]
@cdietrich we're still on time to release a fix, aren't we @merks ?
By the way, Maven artefacts are not affected, only p2 stuff: we could even just release another p2 site (the build qualifier will be increased) and skip the Maven deployment (though our Jenkinsfile should be updated in that respect). Otherwise, we fully release 2.36.1.

In general, I had already proposed not to use fixed versions of such dependencies in the target platform ;)

**Comment by cdietrich** [comment]
I don’t think we did a dot release for years 
And I can’t contribute anything

**Comment by cdietrich** [comment]
yes this is cause my solution would be "live with it"

**Pull request merged**
