### PR TITLE
[490871] Always register Ecore.genmodel

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=490871

**Comment by cdietrich** [comment]
Jenkins test

**Comment by JanKoehnlein** [comment]
Jenkins test

**Comment by cdietrich** [comment]
is it ok to merge this?

**Comment by svenefftinge** [comment]
yes it is

**Pull request merged**
