### PR TITLE
[#3010] AbstractOutlineTest: add @Before and @BeforeEach annotation.

### PR DESCRIPTION
**Pull request by miklossy**

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
Is that required? Isn't the override annotation enough? Moreover there's also the call to super. Wouldn't the added annotations somehow conflict with the Override one? cc @szarnekow

**Comment by miklossy** [comment]
@LorenzoBettini: It was really suprising for me as well, but the annotations have to be repeated, see [javadoc on the BeforeEach](https://github.com/junit-team/junit5/blob/5c7338c166e1e185161f2a82f2863d7900905988/junit-jupiter-api/src/main/java/org/junit/jupiter/api/BeforeEach.java#L41-L43) class.

**Review by LorenzoBettini — APPROVED** [review]
OK, especially if we already do that in other base classes as you said

**Comment by LorenzoBettini** [comment]
@miklossy you might want to rebase on master now that the classgraph issue has been solved

**Comment by miklossy** [comment]
@LorenzoBettini : thanks for the hint, I have just rebased this branch on master.

**Comment by LorenzoBettini** [comment]
@miklossy Thanks! :)

**Comment by miklossy** [comment]
Thank you, @LorenzoBettini for reviewing and merging the changes!

**Pull request merged**
