### PR TITLE
Adding graphql-xtext project to xtext community page.

### PR DESCRIPTION
**Pull request by ashpak-shaikh**
Signed-off-by: Ashpak Shaikh <ashpak_shaikh@intuit.com>

### CODE REVIEW

**Comment by miklossy** [comment]
@ashpak-shaikh Thanks for the Pull Request!

Could you please refer to the GitHub issue #1541 in the commit message, sign the Eclipse Foundation Contributor Agreement and add the sign-off-by clause?

**Comment by ashpak-shaikh** [comment]
@miklossy I have accepted the agreement using the account with ashpak_shaikh@intuit.com as the email address. Do I need to do anything else?

**Comment by cdietrich** [comment]
the tooling s***cks. you need to basically do the commit locally and sign it off. doing stuff from the web-if is not properly recognized. sorry for that.

**Comment by miklossy** [comment]
Nice! You have to add the GitHub issue and the sign-off-by clause to the commit message and force push the change to your fork to trigger the ECA validation again.

**Comment by ashpak-shaikh** [comment]
> Nice! You have to add the GitHub issue and the sign-off-by clause to the commit message and force push the change to your fork to trigger the ECA validation again.

done. Still no success

**Comment by miklossy** [comment]
Please also sing the commit as described in the [contribution guide](https://github.com/eclipse/xtext/blob/master/CONTRIBUTING.md#contribute-via-fork). e.g:
`Signed-off-by: Tamas Miklossy <miklossy@itemis.de>`

**Comment by ashpak-shaikh** [comment]
> Please also sing the commit as described in the [contribution guide](https://github.com/eclipse/xtext/blob/master/CONTRIBUTING.md#contribute-via-fork), similar to [my commit](https://github.com/eclipse/xtext/commit/4fb94785fd9105fcd3f99a85cce4af5a7a3a70ed):
> `Signed-off-by: Tamas Miklossy <miklossy@itemis.de>`

Done

**Comment by cdietrich** [comment]
> Anonymous (56656932+ashpak-shaikh@****.noreply) is not covered by the necessary legal agreements in order to proceed.

=> commit has to be created on a local machine with a git user

or:

we close this PR and @miklossy does create a new one with your changes

**Comment by ashpak-shaikh** [comment]
> > Anonymous (56656932+ashpak-shaikh@****.noreply) is not covered by the necessary legal agreements in order to proceed.
> 
> => commit has to be created on a local machine with a git user
> 
> or:
> 
> we close this PR and @miklossy does create a new one with your changes

Done. Thanks

**Comment by miklossy** [comment]
Now it looks well. @cdietrich If you also agree, please merge this PR.

**Pull request merged**
